# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud Arduosoft RawCms'
    organization: 'arduosoft-1'
    scannerMode: 'MSBuild'
    projectKey: 'arduosoft_RawCMS'
    projectName: 'RawCms'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Registry Arduosoft'
    repository: 'arduosoft/RawCms'
    command: 'buildAndPush'
    Dockerfile: 'docker/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
